stages:
  - test
  - build_standalone
  - build_generic_zip
  - build_installer
  - sign

  
  
  
build_svarog_standalone:
  image: svarog-build-test-image:u1604
  stage: build_standalone
  script:
    - apt-get update && apt-get install -y --no-install-recommends zip unzip tar
    - ./scripts/ci/buildzip.sh
    - mkdir -p dist
    - mv dist/svarog-*-standalone.zip dist/svarog.zip
    - cd dist
    - mkdir svarog
    - unzip svarog.zip -d svarog_temp
    - cd svarog_temp/svarog*standalone
    - mv * ../../svarog/
    - cd ../../../
    - cp -r dist/svarog ./svarog-standalone-package
  tags:
    - docker
  cache:
    paths:
      - .m2/repository
  artifacts:
    name: "svarog_standalone_{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
      - svarog-standalone-package
    
build_svarog_win_zip:
  image: svarog-build-test-image:u1604
  stage: build_generic_zip
  script:
    - apt-get update && apt-get install -y --no-install-recommends zip unzip tar
    - mkdir -p dist
    - cp -r svarog-standalone-package dist/svarog
    - ./installer_builder/scripts/win_build_zip.sh
    - mv dist/svarog_win ./
  tags:
    - docker
  dependencies:
    - build_svarog_standalone
  artifacts:
    name: "svarog_win_{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
      - svarog_win

build_svarog_lin_zip:
  image: svarog-build-test-image:u1604
  stage: build_generic_zip
  script:
    - apt-get update && apt-get install -y --no-install-recommends zip unzip tar
    - mkdir -p dist
    - cp -r svarog-standalone-package dist/svarog
    - ./installer_builder/scripts/linux_build_zip.sh
    - mv dist/svarog_linux ./
  tags:
    - docker
  dependencies:
    - build_svarog_standalone
  artifacts:
    name: "svarog_linux_{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
      - svarog_linux
      
build_svarog_lin_deb:
  image: svarog-build-test-image:u1604
  stage: build_installer
  script:
    - ./installer_builder/scripts/linux_build_deb.sh
  tags:
    - docker
  dependencies:
    - build_svarog_lin_zip
  artifacts:
    name: "svarog_linux_deb_{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
      - svarog.deb

build_svarog_mac:
  image: svarog-build-test-image:u1604
  stage: build_installer
  script:
    - apt-get update && apt-get install -y --no-install-recommends zip unzip tar
    - mkdir -p dist
    - cp -r svarog-standalone-package dist/svarog
    - ./installer_builder/scripts/mac_build.sh
    - mv dist/svarog_mac.app ./
  tags:
    - docker
  dependencies:
    - build_svarog_standalone
  artifacts:
    name: "svarog_mac_{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
      - svarog_mac.app

mvntest:
  image: svarog-build-test-image:u1604
  stage: test
  script:
    - mvn test
    
signdebs:
  image: signdebs-image
  stage: sign
  before_script:
    - apt-get update -qq
    - apt-get install -y gnupg debsigs
  script: ./scripts/ci/signdebs.sh
  dependencies:
    - build_svarog_lin_deb
  artifacts:
    name: "svarog_signed_{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
    - svarog*.deb


